services:
  mariadb:
    build: requirements/mariadb
    volumes:
      - database_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception_network
  nginx:
    build: requirements/nginx
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception_network

volumes:
  wordpress_volume:
    name: wordpress_volume
    driver_opts:
      device: /home/serhouni/Desktop/data/wordpress
      type: none
      o: bind

  database_volume:
    name: database_volume
    driver_opts:
      device: /home/serhouni/Desktop/data/database
      type: none
      o: bind

networks:
  inception_network: