services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb:incep
    volumes:
      - database_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress:incep
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception_network
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx:incep
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception_network

volumes:
  wordpress_volume:
    name: wordpress_volume
    driver_opts:
      device: /home/serhouni/data/wordpress
      type: none
      o: bind

  database_volume:
    name: database_volume
    driver_opts:
      device: /home/serhouni/data/database
      type: none
      o: bind

networks:
  inception_network: