services:
  mariadb:
    build: mariadb
    # volumes:
    #   - database_volume:
    env_file:
      - .env
  wordpress:
    build: wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
  nginx:
    build: nginx
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    ports:
      - "80:80"

volumes:
  wordpress_volume:
#     name: wordpress_volume
    # driver_opts:
    #   device: /Users/serhouni/Desktop/data/
    #   type: none
    #   o: bind
#   # database_volume: